-- Seed mcode_keyword_lookup from DM Common File V11 MachineCodes sheet
-- (218 keywords)
DELETE FROM mcode_keyword_lookup;
INSERT INTO mcode_keyword_lookup (keyword, assigned_m_code, match_type, match_field, priority, is_active) VALUES
  ('0402', '0402', 'word_boundary', 'any', 10, true),
  ('0404', '0402', 'word_boundary', 'any', 11, true),
  ('0603', 'CP', 'word_boundary', 'any', 12, true),
  ('603', 'CP', 'word_boundary', 'any', 13, true),
  ('0606', 'CP', 'word_boundary', 'any', 14, true),
  ('612', 'CP', 'word_boundary', 'any', 15, true),
  ('0805', 'CP', 'word_boundary', 'any', 16, true),
  ('1206', 'CP', 'word_boundary', 'any', 17, true),
  ('1210', 'CP', 'word_boundary', 'any', 18, true),
  ('1212', 'CP', 'word_boundary', 'any', 19, true),
  ('1311', 'CP', 'word_boundary', 'any', 20, true),
  ('1411', 'CP', 'word_boundary', 'any', 21, true),
  ('1808', 'CPEXP', 'word_boundary', 'any', 22, true),
  ('1812', 'CPEXP', 'word_boundary', 'any', 23, true),
  ('1825', 'CPEXP', 'word_boundary', 'any', 24, true),
  ('2010', 'CP', 'word_boundary', 'any', 25, true),
  ('2220', 'CPEXP', 'word_boundary', 'any', 26, true),
  ('2312', 'CP', 'word_boundary', 'any', 27, true),
  ('2512', 'CP', 'word_boundary', 'any', 28, true),
  ('2818', 'IP', 'word_boundary', 'any', 29, true),
  ('2917', 'IP', 'word_boundary', 'any', 30, true),
  ('3216', 'CP', 'word_boundary', 'any', 31, true),
  ('3528', 'CP', 'word_boundary', 'any', 32, true),
  ('3825', 'CP', 'word_boundary', 'any', 33, true),
  ('7343', 'IP', 'word_boundary', 'any', 34, true),
  ('160808', 'CP', 'word_boundary', 'any', 35, true),
  ('100TQFP', 'IP', 'word_boundary', 'any', 36, true),
  ('10msop', 'CPEXP', 'word_boundary', 'any', 37, true),
  ('10VSSOP', 'CPEXP', 'word_boundary', 'any', 38, true),
  ('10-VSSOP', 'CPEXP', 'word_boundary', 'any', 39, true),
  ('14HTSSOP', 'IP', 'word_boundary', 'any', 40, true),
  ('14SO', 'IP', 'word_boundary', 'any', 41, true),
  ('14-SOIC', 'IP', 'word_boundary', 'any', 42, true),
  ('14TSSOP', 'IP', 'word_boundary', 'any', 43, true),
  ('16SOIC', 'IP', 'word_boundary', 'any', 44, true),
  ('16-SOIC', 'IP', 'word_boundary', 'any', 45, true),
  ('16TSSOP', 'IP', 'word_boundary', 'any', 46, true),
  ('20SOIC', 'IP', 'word_boundary', 'any', 47, true),
  ('20-soic', 'IP', 'word_boundary', 'any', 48, true),
  ('20TSSOP', 'IP', 'word_boundary', 'any', 49, true),
  ('24SOIC', 'IP', 'word_boundary', 'any', 50, true),
  ('24SSOP', 'IP', 'word_boundary', 'any', 51, true),
  ('24TSSOP', 'IP', 'word_boundary', 'any', 52, true),
  ('28-SSOP', 'IP', 'word_boundary', 'any', 53, true),
  ('2X1SON', '0402', 'word_boundary', 'any', 54, true),
  ('3528-21', 'CP', 'word_boundary', 'any', 55, true),
  ('4SOP', 'CPEXP', 'word_boundary', 'any', 56, true),
  ('4-sop', 'CPEXP', 'word_boundary', 'any', 57, true),
  ('5SOT', 'CP', 'word_boundary', 'any', 58, true),
  ('6-SOT26', 'CP', 'word_boundary', 'any', 59, true),
  ('6TSOP', 'CP', 'word_boundary', 'any', 60, true),
  ('6TSSOP', 'CP', 'word_boundary', 'any', 61, true),
  ('7343-31', 'IP', 'word_boundary', 'any', 62, true),
  ('7351 Metric', 'IP', 'contains', 'any', 63, true),
  ('8DSOP', 'CPEXP', 'word_boundary', 'any', 64, true),
  ('8MSOP', 'CPEXP', 'word_boundary', 'any', 65, true),
  ('8-SMD', 'IP', 'word_boundary', 'any', 66, true),
  ('8SO', 'CPEXP', 'word_boundary', 'any', 67, true),
  ('8SOIC', 'CPEXP', 'word_boundary', 'any', 68, true),
  ('8-SOIC', 'CPEXP', 'word_boundary', 'any', 69, true),
  ('8TSSOP', 'IP', 'word_boundary', 'any', 70, true),
  ('8VSSOP', 'CPEXP', 'word_boundary', 'any', 71, true),
  ('8WSON', '0402', 'word_boundary', 'any', 72, true),
  ('Aluminum Electrolytic Capacitors', 'IP', 'contains', 'description', 73, true),
  ('axial', 'TH', 'word_boundary', 'any', 74, true),
  ('Cap Alum', 'IP', 'word_boundary', 'any', 75, true),
  ('CAPACITOR ELECT', 'IP', 'contains', 'any', 76, true),
  ('Capacitor Electrolytic', 'IP', 'contains', 'any', 77, true),
  ('CAPACITOR|SMT, 10X10.2(G)', 'IP', 'contains', 'any', 78, true),
  ('CAPACITOR|SMT, 6.3 X 5.8(D)', 'IP', 'contains', 'any', 79, true),
  ('CAPACITOR|SMT, 8 X 6.2(E)', 'IP', 'contains', 'any', 80, true),
  ('CASE A', 'IP', 'word_boundary', 'any', 81, true),
  ('D Pak', 'IP', 'word_boundary', 'any', 82, true),
  ('D0214AC', 'CP', 'word_boundary', 'any', 83, true),
  ('D2 PAK', 'IP', 'word_boundary', 'any', 84, true),
  ('D2pak', 'IP', 'word_boundary', 'any', 85, true),
  ('D2-PAK', 'IP', 'word_boundary', 'any', 86, true),
  ('DFN1006-2', '0402', 'contains', 'any', 87, true),
  ('DFN8', 'CP', 'word_boundary', 'any', 88, true),
  ('DIP', 'TH', 'word_boundary', 'any', 89, true),
  ('DO214AA', 'CP', 'word_boundary', 'any', 90, true),
  ('DO-214AA', 'CP', 'word_boundary', 'any', 91, true),
  ('DO214AB', 'IP', 'word_boundary', 'any', 92, true),
  ('DO-214AB', 'IP', 'word_boundary', 'any', 93, true),
  ('DO214AC', 'CP', 'word_boundary', 'any', 94, true),
  ('DO-221AC', 'CP', 'word_boundary', 'any', 95, true),
  ('DPAK', 'IP', 'word_boundary', 'any', 96, true),
  ('D-PAK', 'IP', 'word_boundary', 'any', 97, true),
  ('D-SUB', 'TH', 'word_boundary', 'any', 98, true),
  ('ECG CAPACITOR ELECT', 'IP', 'contains', 'any', 99, true),
  ('Electrolytic Capacitor', 'IP', 'contains', 'any', 100, true),
  ('Header straight solder pin', 'TH', 'contains', 'any', 101, true),
  ('LQFP144', 'IP', 'word_boundary', 'any', 102, true),
  ('MELF', 'CP', 'word_boundary', 'any', 103, true),
  ('minimelf', 'CP', 'word_boundary', 'any', 104, true),
  ('MSOP8', 'CPEXP', 'word_boundary', 'any', 105, true),
  ('PANASONIC-ECG', 'IP', 'contains', 'any', 106, true),
  ('PC TEST POINT', 'CP', 'contains', 'any', 107, true),
  ('PCB Terminal Strip', 'TH', 'contains', 'any', 108, true),
  ('PDSO5', 'CP', 'word_boundary', 'any', 109, true),
  ('PLCC', 'IP', 'word_boundary', 'any', 110, true),
  ('POWERDI123', 'CP', 'contains', 'any', 111, true),
  ('PowerDI-123', 'CP', 'contains', 'any', 112, true),
  ('PowerDI™ 123', 'CP', 'contains', 'any', 113, true),
  ('QFN', 'IP', 'word_boundary', 'any', 114, true),
  ('QFP', 'IP', 'word_boundary', 'any', 115, true),
  ('Radial', 'TH', 'word_boundary', 'any', 116, true),
  ('RJ45', 'TH', 'word_boundary', 'any', 117, true),
  ('RJ-45', 'TH', 'word_boundary', 'any', 118, true),
  ('SC70', 'CP', 'word_boundary', 'any', 119, true),
  ('SC-70', 'CP', 'word_boundary', 'any', 120, true),
  ('SC705', 'CP', 'word_boundary', 'any', 121, true),
  ('SC70-5', 'CP', 'word_boundary', 'any', 122, true),
  ('SC70-6', 'CP', 'word_boundary', 'any', 123, true),
  ('SC74A', 'CP', 'word_boundary', 'any', 124, true),
  ('SC-74A', 'CP', 'word_boundary', 'any', 125, true),
  ('SC76-2', 'CP', 'word_boundary', 'any', 126, true),
  ('SMA', 'CP', 'word_boundary', 'any', 127, true),
  ('SMB', 'CP', 'word_boundary', 'any', 128, true),
  ('SMC', 'IP', 'word_boundary', 'any', 129, true),
  ('SMCJ', 'IP', 'word_boundary', 'any', 130, true),
  ('SMT 0ZCH Series PTC resettable, 30V, I Hold=200mA, I Trip=400mA @ 23°C', 'CP', 'contains', 'description', 131, true),
  ('SMT, CMOS Clock Oscillator with Enable, 3.3Vdc, 50.000 MHz', 'CPEXP', 'contains', 'description', 132, true),
  ('SO14', 'IP', 'word_boundary', 'any', 133, true),
  ('SO-14', 'IP', 'word_boundary', 'any', 134, true),
  ('SO16', 'IP', 'word_boundary', 'any', 135, true),
  ('SO-16', 'IP', 'word_boundary', 'any', 136, true),
  ('SO4', 'CPEXP', 'word_boundary', 'any', 137, true),
  ('SO6', 'CPEXP', 'word_boundary', 'any', 138, true),
  ('SO8', 'CPEXP', 'word_boundary', 'any', 139, true),
  ('SO-8', 'CPEXP', 'word_boundary', 'any', 140, true),
  ('sod123', 'CP', 'word_boundary', 'any', 141, true),
  ('SOD-123', 'CP', 'word_boundary', 'any', 142, true),
  ('SOD-123F', 'CP', 'word_boundary', 'any', 143, true),
  ('SOD123W', 'CP', 'word_boundary', 'any', 144, true),
  ('SOD-123W', 'CP', 'word_boundary', 'any', 145, true),
  ('SOD128', 'CP', 'word_boundary', 'any', 146, true),
  ('SOD-128-2', 'CP', 'contains', 'any', 147, true),
  ('SOD323', 'CP', 'word_boundary', 'any', 148, true),
  ('SOD-323', '0402', 'word_boundary', 'any', 149, true),
  ('SOD-323F', '0402', 'word_boundary', 'any', 150, true),
  ('SOD523', 'CP', 'word_boundary', 'any', 151, true),
  ('SOD80', 'CP', 'word_boundary', 'any', 152, true),
  ('SOD-9223', '0402', 'word_boundary', 'any', 153, true),
  ('SOD923', '0402', 'word_boundary', 'any', 154, true),
  ('SOD-923', '0402', 'word_boundary', 'any', 155, true),
  ('SOIC16', 'IP', 'word_boundary', 'any', 156, true),
  ('soic8', 'CPEXP', 'word_boundary', 'any', 157, true),
  ('SOIC-8', 'CPEXP', 'word_boundary', 'any', 158, true),
  ('SOP4', 'CPEXP', 'word_boundary', 'any', 159, true),
  ('SOP-4', 'CPEXP', 'word_boundary', 'any', 160, true),
  ('SOT143B', 'CP', 'word_boundary', 'any', 161, true),
  ('SOT223', 'IP', 'word_boundary', 'any', 162, true),
  ('SOT-223', 'IP', 'word_boundary', 'any', 163, true),
  ('SOT23', 'CP', 'word_boundary', 'any', 164, true),
  ('sot-23', 'CP', 'word_boundary', 'any', 165, true),
  ('SOT-23-3', 'CP', 'word_boundary', 'any', 166, true),
  ('SOT25', 'CP', 'word_boundary', 'any', 167, true),
  ('SOT-25-5', 'CP', 'word_boundary', 'any', 168, true),
  ('SOT26', 'CP', 'word_boundary', 'any', 169, true),
  ('SOT323', '0402', 'word_boundary', 'any', 170, true),
  ('SOT-323', '0402', 'word_boundary', 'any', 171, true),
  ('SOT353', 'CP', 'word_boundary', 'any', 172, true),
  ('SOT363', 'CP', 'word_boundary', 'any', 173, true),
  ('SOT-363', 'CP', 'word_boundary', 'any', 174, true),
  ('SOT5', 'CP', 'word_boundary', 'any', 175, true),
  ('SOT523', 'CP', 'word_boundary', 'any', 176, true),
  ('SOT-583', '0402', 'word_boundary', 'any', 177, true),
  ('SOT-7538', 'CP', 'word_boundary', 'any', 178, true),
  ('SOT-89', 'CPEXP', 'word_boundary', 'any', 179, true),
  ('SOT9X3', '0402', 'word_boundary', 'any', 180, true),
  ('SOW16', 'IP', 'word_boundary', 'any', 181, true),
  ('SOW-16', 'IP', 'word_boundary', 'any', 182, true),
  ('SOW20', 'IP', 'word_boundary', 'any', 183, true),
  ('SOW28', 'IP', 'word_boundary', 'any', 184, true),
  ('SSMINI2', 'CP', 'word_boundary', 'any', 185, true),
  ('SSOP28', 'IP', 'word_boundary', 'any', 186, true),
  ('SSOP-28', 'IP', 'word_boundary', 'any', 187, true),
  ('SSOP5', 'CP', 'word_boundary', 'any', 188, true),
  ('T/H', 'TH', 'word_boundary', 'any', 189, true),
  ('TERM BLOCK', 'TH', 'contains', 'any', 190, true),
  ('TERM BLOCK HDR', 'TH', 'contains', 'any', 191, true),
  ('TH', 'TH', 'word_boundary', 'any', 192, true),
  ('TH,', 'TH', 'word_boundary', 'any', 193, true),
  ('Through hole', 'TH', 'contains', 'any', 194, true),
  ('Thru-Hole', 'TH', 'contains', 'any', 195, true),
  ('THT', 'TH', 'word_boundary', 'any', 196, true),
  ('TO-236-3', 'CP', 'word_boundary', 'any', 197, true),
  ('TO236AB', 'CP', 'word_boundary', 'any', 198, true),
  ('TO-236AB', 'CP', 'word_boundary', 'any', 199, true),
  ('TO252', 'IP', 'word_boundary', 'any', 200, true),
  ('TO252-3', 'IP', 'word_boundary', 'any', 201, true),
  ('TO263', 'IP', 'word_boundary', 'any', 202, true),
  ('TO-263', 'IP', 'word_boundary', 'any', 203, true),
  ('to-268', 'IP', 'word_boundary', 'any', 204, true),
  ('TO92', 'TH', 'word_boundary', 'any', 205, true),
  ('TO92-3', 'TH', 'word_boundary', 'any', 206, true),
  ('TQFP', 'IP', 'word_boundary', 'any', 207, true),
  ('TQFP144', 'IP', 'word_boundary', 'any', 208, true),
  ('TSOT-6', 'CP', 'word_boundary', 'any', 209, true),
  ('TSSOP14', 'IP', 'word_boundary', 'any', 210, true),
  ('TSSOP-14', 'CPEXP', 'word_boundary', 'any', 211, true),
  ('TSSOP16', 'IP', 'word_boundary', 'any', 212, true),
  ('TSSOP-16', 'IP', 'word_boundary', 'any', 213, true),
  ('TSSOP20', 'IP', 'word_boundary', 'any', 214, true),
  ('TSSOP24', 'IP', 'word_boundary', 'any', 215, true),
  ('TSSOP48', 'IP', 'word_boundary', 'any', 216, true),
  ('TUMD2M', 'CP', 'word_boundary', 'any', 217, true),
  ('VMN2M', '0402', 'word_boundary', 'any', 218, true),
  ('WSON8', 'CP', 'word_boundary', 'any', 219, true),
  ('X1-DFN100', '0402', 'contains', 'any', 220, true),
  ('TSMT3', 'CP', 'word_boundary', 'any', 221, true),
  ('PICOSTAR', '0402', 'word_boundary', 'any', 222, true),
  ('SOT-26', 'CP', 'word_boundary', 'any', 223, true),
  ('1008', 'CP', 'word_boundary', 'any', 224, true),
  ('1005', '0402', 'word_boundary', 'any', 225, true),
  ('SOT-25', 'CP', 'word_boundary', 'any', 226, true),
  ('TO-277A', 'CPEXP', 'word_boundary', 'any', 227, true);

-- Seed m_code_rules from DM Common File V11 Admin sheet
-- (43 rules)
DELETE FROM m_code_rules;
INSERT INTO m_code_rules (rule_id, priority, layer, field_1, operator_1, value_1, field_2, operator_2, value_2, assigned_m_code, description, is_active) VALUES
  ('PAR-01', 100, 2, 'mounting_type', 'equals', 'Through Hole', NULL, NULL, NULL, 'TH', 'If Mounting Type is equals to "Through Hole" then it is TH', true),
  ('PAR-02', 101, 2, 'mounting_type', 'equals', 'Surface Mount, Through Hole', NULL, NULL, NULL, 'MANSMT', 'If Mounting Type is equals to "Surface Mount, Through Hole" then it is MANSMT', true),
  ('PAR-03', 102, 2, 'description', 'contains', 'End Launch Solder', NULL, NULL, NULL, 'TH', 'If Product Description include keyword "End Launch Solder" then it is TH', true),
  ('PAR-04', 103, 2, 'sub_category', 'equals', 'Slide Switches', 'mounting_type', 'equals', 'Surface Mount', 'IP', 'If Sub-Category is equals to "Slide Switches" and Mounting Type is equals to "Surface Mount" then it is IP', true),
  ('PAR-05', 104, 2, 'sub_category', 'equals', 'Tactile Switches', 'mounting_type', 'equals', 'Surface Mount', 'IP', 'If Sub-Category is equals to "Tactile Switches" and Mounting Type is equals to "Surface Mount" then it is IP', true),
  ('PAR-06', 105, 2, 'sub_category', 'equals', 'Tactile Switches', 'mounting_type', 'equals', 'Surface Mount, Right Angle', 'IP', 'If Sub-Category is equals to "Tactile Switches" and Mounting Type is equals to "Surface Mount" then it is IP', true),
  ('PAR-07', 106, 2, 'sub_category', 'equals', 'Slide Switches', NULL, NULL, NULL, 'TH', 'If Sub-Category is equals to "Slide Switches" then it is TH', true),
  ('PAR-08', 107, 2, 'sub_category', 'equals', 'Tactile Switches', NULL, NULL, NULL, 'TH', 'If Sub-Category is equals to "Tactile Switches" then it is TH', true),
  ('PAR-09', 108, 2, 'sub_category', 'equals', 'RFI and EMI - Contacts, Fingerstock and Gaskets', NULL, NULL, NULL, 'Accs', 'If Sub-Category is equals to "RFI and EMI - Contacts, Fingerstock and Gaskets" then it is Accs', true),
  ('PAR-10', 109, 2, 'sub_category', 'equals', 'RF Shields', 'description', 'contains', 'Surface Mount', 'MANSMT', 'If Sub-Category is equals to "RF Shields" and Product Description include keyword "Surface Mount" then it is MANSMT', true),
  ('PAR-11', 110, 2, 'sub_category', 'equals', 'RF Shields', NULL, NULL, NULL, 'MEC', 'If Sub-Category is equals to "RF Shields" then it is MEC', true),
  ('PAR-12', 111, 2, 'sub_category', 'equals', 'Ferrite Cores', NULL, NULL, NULL, 'MEC', 'If Sub-Category is equals to "Ferrite Cores" then it is MEC', true),
  ('PAR-13', 112, 2, 'description', 'contains', 'Standoff', 'features', 'equals', 'Surface Mount', 'MANSMT', 'If Product Description include keyword "Standoff" and Features is equals to "Surface Mount" then it is MANSMT', true),
  ('PAR-14', 113, 2, 'description', 'contains', 'Standoff', NULL, NULL, NULL, 'MEC', 'If Product Description include keyword "Standoff" then it is MEC', true),
  ('PAR-15', 114, 2, 'description', 'contains', 'HEATSINK', 'attachment_method', 'equals', 'Bolt On', 'MEC', 'If Product Description include keyword "HEATSINK" and Attachment Method is equals to "Bolt On" then it is MEC', true),
  ('PAR-16', 115, 2, 'description', 'contains', 'HEATSINK', NULL, NULL, NULL, 'MANSMT', 'If Product Description include keyword "HEATSINK" then it is MANSMT', true),
  ('PAR-17', 116, 2, 'description', 'contains', 'DPAK TO-252', NULL, NULL, NULL, 'MANSMT', 'If Product Description include keyword "DPAK TO-252" then it is MANSMT', true),
  ('PAR-22', 117, 2, 'description', 'contains', 'Pin', 'description', 'contains', 'Crimp', 'CABLE', 'If Product Description include keyword "Pin" and Product Description include "Crimp" then it is CABLE', true),
  ('PAR-23', 118, 2, 'category', 'equals', 'Connectors, Interconnects', 'mounting_type', 'equals', 'Surface Mount', 'MANSMT', 'If Category is equals to "Connectors, Interconnects" and Mounting Type is equals to "Surface Mount" then it is MANSMT', true),
  ('PAR-24', 119, 2, 'description', 'contains', 'Connector Header', 'mounting_type', 'equals', 'Surface Mount', 'MANSMT', 'If Product Description include keyword "Connector Header" and Mounting Type is equals to "Surface Mount" then it is MANSMT', true),
  ('PAR-25', 120, 2, 'category', 'equals', 'Connectors, Interconnects', 'description', 'contains', 'Surface Mount', 'MANSMT', 'If Category is equals to "Connectors, Interconnects" and Product Description include keyword "Surface Mount" then it is MANSMT', true),
  ('PAR-26', 121, 2, 'category', 'equals', 'Connectors, Interconnects', 'description', 'contains', 'SMD', 'MANSMT', 'If Category is equals to "Connectors, Interconnects" and Product Description include keyword "SMD" then it is MANSMT', true),
  ('PAR-27', 122, 2, 'description', 'contains', 'Connector Header position', 'description', 'not_contains', 'SMT, SMD, SURFACE MOUNT', 'TH', 'If Product Description include keyword "Connector Header position" and Product Description does not include "SMT, SMD, SURFACE MOUNT" then it is TH', true),
  ('PAR-28', 123, 2, 'category', 'equals', 'Connectors, Interconnects', 'description', 'not_contains', 'SMT, SMD, SURFACE MOUNT', 'TH', 'If Category is equals to "Connectors, Interconnects" and Product Description not include keyword "SMT, SMD, SURFACE MOUNT" then it is TH', true),
  ('PAR-29', 124, 2, 'category', 'equals', 'Connectors, Interconnects', NULL, NULL, NULL, 'TH', 'If Category is equals to "Connectors, Interconnects" then it is TH', true),
  ('PAR-30', 125, 2, 'sub_category', 'equals', 'Film Capacitors', 'mounting_type', 'equals', 'Chassis Mount', 'TH', 'If Sub-Category is equals to "Film Capacitors" and Mounting Type is equals to "Chassis Mount" then it is TH', true),
  ('PAR-31', 126, 2, 'sub_category', 'equals', 'Film Capacitors', 'mounting_type', 'equals', 'Chassis Mount, Requires Holder/Bracket', 'TH', 'If Sub-Category is equals to "Film Capacitors" and Mounting Type is equals to "Chassis Mount, Requires Holder/Bracket" then it is TH', true),
  ('PAR-32', 127, 2, 'sub_category', 'equals', 'Film Capacitors', 'mounting_type', 'equals', 'Chassis, Stud Mount', 'TH', 'If Sub-Category is equals to "Film Capacitors" and Mounting Type is equals to "Chassis, Stud Mount" then it is TH', true),
  ('PAR-33', 128, 2, 'sub_category', 'equals', 'Film Capacitors', 'mounting_type', 'equals', 'Requires Holder', 'TH', 'If Sub-Category is equals to "Film Capacitors" and Mounting Type is equals to "Requires Holder" then it is TH', true),
  ('PAR-34', 129, 2, 'sub_category', 'equals', 'Film Capacitors', 'mounting_type', 'equals', 'Through Hole', 'TH', 'If Sub-Category is equals to "Film Capacitors" and Mounting Type is equals to "Through Hole" then it is TH', true),
  ('PAR-35', 130, 2, 'mounting_type', 'equals', 'PCB, Through Hole', NULL, NULL, NULL, 'TH', 'If Mounting Type is equals to "PCB, Through Hole" then it is TH', true),
  ('PAR-36', 131, 2, 'mounting_type', 'equals', 'PCB, Surface Mount', NULL, NULL, NULL, 'MANSMT', 'If Mounting Type is equals to "PCB, Surface Mount" then it is MANSMT', true),
  ('PAR-37', 132, 2, 'description', 'contains', 'Battery Insulator', NULL, NULL, NULL, 'Accs', 'If Product Description include keyword "Battery Insulator" then it is Accs', true),
  ('PAR-38', 133, 2, 'sub_category', 'equals', 'Card Guides', NULL, NULL, NULL, 'Accs', 'If Sub-Category is equals to "Card Guides" then it is Accs', true),
  ('PAR-39', 134, 2, 'category', 'equals', 'Cables, Wires - Management', NULL, NULL, NULL, 'CABLE', 'If Category is equals to "Cables, Wires - Management" then it is CABLE', true),
  ('PAR-40', 135, 2, 'category', 'equals', 'Development Boards, Kits, Programmers', NULL, NULL, NULL, 'DEV B', 'If Category is equals to "Development Boards, Kits, Programmers" then it is DEV B', true),
  ('PAR-41', 136, 2, 'description', 'contains', 'Spacer', NULL, NULL, NULL, 'Accs', 'If Product Description include keyword "Spacer" then it is Accs', true),
  ('PAR-42', 137, 2, 'sub_category', 'equals', 'Board Supports', NULL, NULL, NULL, 'MEC', 'If Sub-Category is equals to "Board Supports" then it is MEC', true),
  ('PAR-43', 138, 2, 'description', 'contains', 'Clip', NULL, NULL, NULL, 'Accs', 'If Product Description include keyword "Clip" then it is Accs', true),
  ('PAR-44', 139, 2, 'description', 'contains', 'Clamp', NULL, NULL, NULL, 'Accs', 'If Product Description include keyword "Clamp" then it is Accs', true),
  ('PAR-45', 140, 2, 'description', 'contains', 'Relay', 'description', 'contains', 'Surface Mount', 'IP', 'If Product Description include keyword "Relay" and Product Description include "Surface Mount" then it is IP', true),
  ('PAR-46', 141, 2, 'mounting_type', 'equals', 'Panel, PCB Through Hole', NULL, NULL, NULL, 'TH', 'If Mounting Type is equals to "Panel, PCB Through Hole" then it is TH', true),
  ('PAR-47', 142, 2, 'mounting_type', 'equals', 'Panel Mount', NULL, NULL, NULL, 'TH', 'If Mounting Type is equals to "Panel Mount" then it is TH', true);
