-- ============================================================================
-- Migration 034 — Full reseed from DM V11 CSV + VBA pricing defaults
-- ============================================================================
-- 1) Truncates + reloads mcode_keyword_lookup from machine_codes.csv
-- 2) Truncates + reloads m_code_rules from admin_par_rules.csv
-- 3) Updates app_settings.pricing with values sourced from VBA code:
--    - Calculation_V1.bas:121-122 (shipping $200, pcb_markup 30%)
--    - Generate_TIME_File_V4.bas:858-863 (labour $130/hr, SMT $165/hr,
--      component_markup 30%)
--
-- M-code normalization: Excel strips leading zeros from numeric cells,
-- so the MachineCodes sheet stores '0402' as integer 402. The seed CSV
-- reflects the raw export; this SQL maps '402' → '0402' at insert time.
-- ============================================================================

BEGIN;

-- PART 1 of 3: Reseed m_code_rules from admin_par_rules.csv --------------
TRUNCATE public.m_code_rules RESTART IDENTITY;
INSERT INTO public.m_code_rules
  (rule_id, priority, layer, field_1, operator_1, value_1,
   field_2, operator_2, value_2, assigned_m_code, description, is_active)
VALUES
  ('PAR-01', 100, 2, 'mounting_type', 'equals', 'Through Hole', NULL, NULL, NULL, 'TH', 'If Mounting Type is equals to "Through Hole" then it is TH', true),
  ('PAR-02', 101, 2, 'mounting_type', 'equals', 'Surface Mount, Through Hole', NULL, NULL, NULL, 'MANSMT', 'If Mounting Type is equals to "Surface Mount, Through Hole" then it is MANSMT', true),
  ('PAR-02A', 102, 2, 'mounting_type', 'equals', 'Panel Mount, Through Hole, Right Angle', NULL, NULL, NULL, 'TH', NULL, true),
  ('PAR-03', 103, 2, 'description', 'contains', 'End Launch Solder', NULL, NULL, NULL, 'TH', 'If Product Description include keyword "End Launch Solder" then it is TH', true),
  ('PAR-04', 104, 2, 'sub_category', 'equals', 'Slide Switches', 'mounting_type', 'equals', 'Surface Mount', 'IP', 'If Sub-Category is equals to "Slide Switches" and Mounting Type is equals to "Surface Mount" then it is IP', true),
  ('PAR-05', 105, 2, 'sub_category', 'equals', 'Tactile Switches', 'mounting_type', 'equals', 'Surface Mount', 'IP', 'If Sub-Category is equals to "Tactile Switches" and Mounting Type is equals to "Surface Mount" then it is IP', true),
  ('PAR-06', 106, 2, 'sub_category', 'equals', 'Tactile Switches', 'mounting_type', 'equals', 'Surface Mount, Right Angle', 'IP', 'If Sub-Category is equals to "Tactile Switches" and Mounting Type is equals to "Surface Mount" then it is IP', true),
  ('PAR-07', 107, 2, 'sub_category', 'equals', 'Slide Switches', NULL, NULL, NULL, 'TH', 'If Sub-Category is equals to "Slide Switches" then it is TH', true),
  ('PAR-08', 108, 2, 'sub_category', 'equals', 'Tactile Switches', NULL, NULL, NULL, 'TH', 'If Sub-Category is equals to "Tactile Switches" then it is TH', true),
  ('PAR-09', 109, 2, 'sub_category', 'equals', 'RFI and EMI - Contacts, Fingerstock and Gaskets', NULL, NULL, NULL, 'Accs', 'If Sub-Category is equals to "RFI and EMI - Contacts, Fingerstock and Gaskets" then it is Accs', true),
  ('PAR-10', 110, 2, 'sub_category', 'equals', 'RF Shields', 'description', 'contains', 'Surface Mount', 'MANSMT', 'If Sub-Category is equals to "RF Shields" and Product Description include keyword "Surface Mount" then it is MANSMT', true),
  ('PAR-11', 111, 2, 'sub_category', 'equals', 'RF Shields', NULL, NULL, NULL, 'MEC', 'If Sub-Category is equals to "RF Shields" then it is MEC', true),
  ('PAR-12', 112, 2, 'sub_category', 'equals', 'Ferrite Cores', NULL, NULL, NULL, 'MEC', 'If Sub-Category is equals to "Ferrite Cores" then it is MEC', true),
  ('PAR-13', 113, 2, 'description', 'contains', 'Standoff', 'features', 'equals', 'Surface Mount', 'MANSMT', 'If Product Description include keyword "Standoff" and Features is equals to "Surface Mount" then it is MANSMT', true),
  ('PAR-14', 114, 2, 'description', 'contains', 'Standoff', NULL, NULL, NULL, 'MEC', 'If Product Description include keyword "Standoff" then it is MEC', true),
  ('PAR-15', 115, 2, 'description', 'contains', 'HEATSINK', 'attachment_method', 'equals', 'Bolt On', 'MEC', 'If Product Description include keyword "HEATSINK" and Attachment Method is equals to "Bolt On" then it is MEC', true),
  ('PAR-16', 116, 2, 'description', 'contains', 'HEATSINK', NULL, NULL, NULL, 'MANSMT', 'If Product Description include keyword "HEATSINK" then it is MANSMT', true),
  ('PAR-17', 117, 2, 'description', 'contains', 'DPAK TO-252', NULL, NULL, NULL, 'MANSMT', 'If Product Description include keyword "DPAK TO-252" then it is MANSMT', true),
  ('PAR-18', 118, 2, 'size', 'in_range', '{{size table}}', NULL, NULL, NULL, '{{respective Mcode}}', 'If Size / Dimension is in range with size table then respective Mcode will be assigned', true),
  ('PAR-19', 119, 2, 'diameter', 'in_range', '{{size table}}', NULL, NULL, NULL, '{{respective Mcode}}', 'If Size / Dimension is in range with size table then respective Mcode will be assigned', true),
  ('PAR-20', 120, 2, 'package_case', 'contains', '{{keyword array}}', NULL, NULL, NULL, '{{respective Mcode}}', 'If Package / Case include keyword from MachineCodes sheet then the respective Mcode is assigned', true),
  ('PAR-21', 121, 2, 'description', 'contains', '{{keyword array}}', NULL, NULL, NULL, '{{respective Mcode}}', 'If Product Description include keyword from MachineCodes sheet then the respective Mcode is assigned', true),
  ('PAR-22', 122, 2, 'description', 'contains', 'Pin', 'description', 'contains', 'Crimp', 'CABLE', 'If Product Description include keyword "Pin" and Product Description include "Crimp" then it is CABLE', true),
  ('PAR-23', 123, 2, 'category', 'equals', 'Connectors, Interconnects', 'mounting_type', 'equals', 'Surface Mount', 'MANSMT', 'If Category is equals to "Connectors, Interconnects" and Mounting Type is equals to "Surface Mount" then it is MANSMT', true),
  ('PAR-24', 124, 2, 'description', 'contains', 'Connector Header', 'mounting_type', 'equals', 'Surface Mount', 'MANSMT', 'If Product Description include keyword "Connector Header" and Mounting Type is equals to "Surface Mount" then it is MANSMT', true),
  ('PAR-25', 125, 2, 'category', 'equals', 'Connectors, Interconnects', 'description', 'contains', 'Surface Mount', 'MANSMT', 'If Category is equals to "Connectors, Interconnects" and Product Description include keyword "Surface Mount" then it is MANSMT', true),
  ('PAR-26', 126, 2, 'category', 'equals', 'Connectors, Interconnects', 'description', 'contains', 'SMD', 'MANSMT', 'If Category is equals to "Connectors, Interconnects" and Product Description include keyword "SMD" then it is MANSMT', true),
  ('PAR-27', 127, 2, 'description', 'contains', 'Connector Header position', 'description', 'not_contains', 'SMT, SMD, SURFACE MOUNT', 'TH', 'If Product Description include keyword "Connector Header position" and Product Description does not include "SMT, SMD, SURFACE MOUNT" then it is TH', true),
  ('PAR-28', 128, 2, 'category', 'equals', 'Connectors, Interconnects', 'description', 'not_contains', 'SMT, SMD, SURFACE MOUNT', 'TH', 'If Category is equals to "Connectors, Interconnects" and Product Description not include keyword "SMT, SMD, SURFACE MOUNT" then it is TH', true),
  ('PAR-29', 129, 2, 'category', 'equals', 'Connectors, Interconnects', NULL, NULL, NULL, 'TH', 'If Category is equals to "Connectors, Interconnects" then it is TH', true),
  ('PAR-30', 130, 2, 'sub_category', 'equals', 'Film Capacitors', 'mounting_type', 'equals', 'Chassis Mount', 'TH', 'If Sub-Category is equals to "Film Capacitors" and Mounting Type is equals to "Chassis Mount" then it is TH', true),
  ('PAR-31', 131, 2, 'sub_category', 'equals', 'Film Capacitors', 'mounting_type', 'equals', 'Chassis Mount, Requires Holder/Bracket', 'TH', 'If Sub-Category is equals to "Film Capacitors" and Mounting Type is equals to "Chassis Mount, Requires Holder/Bracket" then it is TH', true),
  ('PAR-32', 132, 2, 'sub_category', 'equals', 'Film Capacitors', 'mounting_type', 'equals', 'Chassis, Stud Mount', 'TH', 'If Sub-Category is equals to "Film Capacitors" and Mounting Type is equals to "Chassis, Stud Mount" then it is TH', true),
  ('PAR-33', 133, 2, 'sub_category', 'equals', 'Film Capacitors', 'mounting_type', 'equals', 'Requires Holder', 'TH', 'If Sub-Category is equals to "Film Capacitors" and Mounting Type is equals to "Requires Holder" then it is TH', true),
  ('PAR-34', 134, 2, 'sub_category', 'equals', 'Film Capacitors', 'mounting_type', 'equals', 'Through Hole', 'TH', 'If Sub-Category is equals to "Film Capacitors" and Mounting Type is equals to "Through Hole" then it is TH', true),
  ('PAR-35', 135, 2, 'mounting_type', 'equals', 'PCB, Through Hole', NULL, NULL, NULL, 'TH', 'If Mounting Type is equals to "PCB, Through Hole" then it is TH', true),
  ('PAR-36', 136, 2, 'mounting_type', 'equals', 'PCB, Surface Mount', NULL, NULL, NULL, 'MANSMT', 'If Mounting Type is equals to "PCB, Surface Mount" then it is MANSMT', true),
  ('PAR-37', 137, 2, 'description', 'contains', 'Battery Insulator', NULL, NULL, NULL, 'Accs', 'If Product Description include keyword "Battery Insulator" then it is Accs', true),
  ('PAR-38', 138, 2, 'sub_category', 'equals', 'Card Guides', NULL, NULL, NULL, 'Accs', 'If Sub-Category is equals to "Card Guides" then it is Accs', true),
  ('PAR-39', 139, 2, 'category', 'equals', 'Cables, Wires - Management', NULL, NULL, NULL, 'CABLE', 'If Category is equals to "Cables, Wires - Management" then it is CABLE', true),
  ('PAR-40', 140, 2, 'category', 'equals', 'Development Boards, Kits, Programmers', NULL, NULL, NULL, 'DEV B', 'If Category is equals to "Development Boards, Kits, Programmers" then it is DEV B', true),
  ('PAR-41', 141, 2, 'description', 'contains', 'Spacer', NULL, NULL, NULL, 'Accs', 'If Product Description include keyword "Spacer" then it is Accs', true),
  ('PAR-42', 142, 2, 'sub_category', 'equals', 'Board Supports', NULL, NULL, NULL, 'MEC', 'If Sub-Category is equals to "Board Supports" then it is MEC', true),
  ('PAR-43', 143, 2, 'description', 'contains', 'Clip', NULL, NULL, NULL, 'Accs', 'If Product Description include keyword "Clip" then it is Accs', true),
  ('PAR-44', 144, 2, 'description', 'contains', 'Clamp', NULL, NULL, NULL, 'Accs', 'If Product Description include keyword "Clamp" then it is Accs', true),
  ('PAR-45', 145, 2, 'description', 'contains', 'Relay', 'description', 'contains', 'Surface Mount', 'IP', 'If Product Description include keyword "Relay" and Product Description include "Surface Mount" then it is IP', true),
  ('PAR-46', 146, 2, 'mounting_type', 'equals', 'Panel, PCB Through Hole', NULL, NULL, NULL, 'TH', 'If Mounting Type is equals to "Panel, PCB Through Hole" then it is TH', true),
  ('PAR-47', 147, 2, 'mounting_type', 'equals', 'Panel Mount', NULL, NULL, NULL, 'TH', 'If Mounting Type is equals to "Panel Mount" then it is TH', true);

-- PART 2 of 3: Reseed mcode_keyword_lookup from machine_codes.csv --------
TRUNCATE public.mcode_keyword_lookup RESTART IDENTITY;
INSERT INTO public.mcode_keyword_lookup
  (keyword, assigned_m_code, match_type, match_field, priority, is_active)
VALUES
  ('0402', '0402', 'word_boundary', 'any', 100, true),
  ('0404', '0402', 'word_boundary', 'any', 101, true),
  ('0603', 'CP', 'word_boundary', 'any', 102, true),
  ('603', 'CP', 'word_boundary', 'any', 103, true),
  ('0606', 'CP', 'word_boundary', 'any', 104, true),
  ('612', 'CP', 'word_boundary', 'any', 105, true),
  ('0805', 'CP', 'word_boundary', 'any', 106, true),
  ('1206', 'CP', 'word_boundary', 'any', 107, true),
  ('1210', 'CP', 'word_boundary', 'any', 108, true),
  ('1212', 'CP', 'word_boundary', 'any', 109, true),
  ('1311', 'CP', 'word_boundary', 'any', 110, true),
  ('1411', 'CP', 'word_boundary', 'any', 111, true),
  ('1808', 'CPEXP', 'word_boundary', 'any', 112, true),
  ('1812', 'CPEXP', 'word_boundary', 'any', 113, true),
  ('1825', 'CPEXP', 'word_boundary', 'any', 114, true),
  ('2010', 'CP', 'word_boundary', 'any', 115, true),
  ('2220', 'CPEXP', 'word_boundary', 'any', 116, true),
  ('2312', 'CP', 'word_boundary', 'any', 117, true),
  ('2512', 'CP', 'word_boundary', 'any', 118, true),
  ('2818', 'IP', 'word_boundary', 'any', 119, true),
  ('2917', 'IP', 'word_boundary', 'any', 120, true),
  ('3216', 'CP', 'word_boundary', 'any', 121, true),
  ('3528', 'CP', 'word_boundary', 'any', 122, true),
  ('3825', 'CP', 'word_boundary', 'any', 123, true),
  ('7343', 'IP', 'word_boundary', 'any', 124, true),
  ('160808', 'CP', 'word_boundary', 'any', 125, true),
  ('100TQFP', 'IP', 'word_boundary', 'any', 126, true),
  ('10msop', 'CPEXP', 'word_boundary', 'any', 127, true),
  ('10VSSOP', 'CPEXP', 'word_boundary', 'any', 128, true),
  ('10-VSSOP', 'CPEXP', 'word_boundary', 'any', 129, true),
  ('14HTSSOP', 'IP', 'word_boundary', 'any', 130, true),
  ('14SO', 'IP', 'word_boundary', 'any', 131, true),
  ('14-SOIC', 'IP', 'word_boundary', 'any', 132, true),
  ('14TSSOP', 'IP', 'word_boundary', 'any', 133, true),
  ('16SOIC', 'IP', 'word_boundary', 'any', 134, true),
  ('16-SOIC', 'IP', 'word_boundary', 'any', 135, true),
  ('16TSSOP', 'IP', 'word_boundary', 'any', 136, true),
  ('20SOIC', 'IP', 'word_boundary', 'any', 137, true),
  ('20-soic', 'IP', 'word_boundary', 'any', 138, true),
  ('20TSSOP', 'IP', 'word_boundary', 'any', 139, true),
  ('24SOIC', 'IP', 'word_boundary', 'any', 140, true),
  ('24SSOP', 'IP', 'word_boundary', 'any', 141, true),
  ('24TSSOP', 'IP', 'word_boundary', 'any', 142, true),
  ('28-SSOP', 'IP', 'word_boundary', 'any', 143, true),
  ('2X1SON', '0402', 'word_boundary', 'any', 144, true),
  ('3528-21', 'CP', 'word_boundary', 'any', 145, true),
  ('4SOP', 'CPEXP', 'word_boundary', 'any', 146, true),
  ('4-sop', 'CPEXP', 'word_boundary', 'any', 147, true),
  ('5SOT', 'CP', 'word_boundary', 'any', 148, true),
  ('6-SOT26', 'CP', 'word_boundary', 'any', 149, true),
  ('6TSOP', 'CP', 'word_boundary', 'any', 150, true),
  ('6TSSOP', 'CP', 'word_boundary', 'any', 151, true),
  ('7343-31', 'IP', 'word_boundary', 'any', 152, true),
  ('7351 Metric', 'IP', 'word_boundary', 'any', 153, true),
  ('8DSOP', 'CPEXP', 'word_boundary', 'any', 154, true),
  ('8MSOP', 'CPEXP', 'word_boundary', 'any', 155, true),
  ('8-SMD', 'IP', 'word_boundary', 'any', 156, true),
  ('8SO', 'CPEXP', 'word_boundary', 'any', 157, true),
  ('8SOIC', 'CPEXP', 'word_boundary', 'any', 158, true),
  ('8-SOIC', 'CPEXP', 'word_boundary', 'any', 159, true),
  ('8TSSOP', 'IP', 'word_boundary', 'any', 160, true),
  ('8VSSOP', 'CPEXP', 'word_boundary', 'any', 161, true),
  ('8WSON', '0402', 'word_boundary', 'any', 162, true),
  ('Aluminum Electrolytic Capacitors', 'IP', 'word_boundary', 'any', 163, true),
  ('axial', 'TH', 'word_boundary', 'any', 164, true),
  ('Cap Alum', 'IP', 'word_boundary', 'any', 165, true),
  ('CAPACITOR ELECT', 'IP', 'word_boundary', 'any', 166, true),
  ('Capacitor Electrolytic', 'IP', 'word_boundary', 'any', 167, true),
  ('CAPACITOR|SMT, 10X10.2(G)', 'IP', 'word_boundary', 'any', 168, true),
  ('CAPACITOR|SMT, 6.3 X 5.8(D)', 'IP', 'word_boundary', 'any', 169, true),
  ('CAPACITOR|SMT, 8 X 6.2(E)', 'IP', 'word_boundary', 'any', 170, true),
  ('CASE A', 'IP', 'word_boundary', 'any', 171, true),
  ('D Pak', 'IP', 'word_boundary', 'any', 172, true),
  ('D0214AC', 'CP', 'word_boundary', 'any', 173, true),
  ('D2 PAK', 'IP', 'word_boundary', 'any', 174, true),
  ('D2pak', 'IP', 'word_boundary', 'any', 175, true),
  ('D2-PAK', 'IP', 'word_boundary', 'any', 176, true),
  ('DFN1006-2', '0402', 'word_boundary', 'any', 177, true),
  ('DFN8', 'CP', 'word_boundary', 'any', 178, true),
  ('DIP', 'TH', 'word_boundary', 'any', 179, true),
  ('DO214AA', 'CP', 'word_boundary', 'any', 180, true),
  ('DO-214AA', 'CP', 'word_boundary', 'any', 181, true),
  ('DO214AB', 'IP', 'word_boundary', 'any', 182, true),
  ('DO-214AB', 'IP', 'word_boundary', 'any', 183, true),
  ('DO214AC', 'CP', 'word_boundary', 'any', 184, true),
  ('DO-221AC', 'CP', 'word_boundary', 'any', 185, true),
  ('DPAK', 'IP', 'word_boundary', 'any', 186, true),
  ('D-PAK', 'IP', 'word_boundary', 'any', 187, true),
  ('D-SUB', 'TH', 'word_boundary', 'any', 188, true),
  ('ECG CAPACITOR ELECT', 'IP', 'word_boundary', 'any', 189, true),
  ('Electrolytic Capacitor', 'IP', 'word_boundary', 'any', 190, true),
  ('Header straight solder pin', 'TH', 'word_boundary', 'any', 191, true),
  ('LITE-ON INC  LED SMT LED Blue Clear 466nm', 'CP', 'word_boundary', 'any', 192, true),
  ('LQFP144', 'IP', 'word_boundary', 'any', 193, true),
  ('MELF', 'CP', 'word_boundary', 'any', 194, true),
  ('minimelf', 'CP', 'word_boundary', 'any', 195, true),
  ('MSOP8', 'CPEXP', 'word_boundary', 'any', 196, true),
  ('PANASONIC-ECG', 'IP', 'word_boundary', 'any', 197, true),
  ('PC TEST POINT', 'CP', 'word_boundary', 'any', 198, true),
  ('PCB Terminal Strip', 'TH', 'word_boundary', 'any', 199, true),
  ('PDSO5', 'CP', 'word_boundary', 'any', 200, true),
  ('PLCC', 'IP', 'word_boundary', 'any', 201, true),
  ('POWERDI123', 'CP', 'word_boundary', 'any', 202, true),
  ('PowerDI-123', 'CP', 'word_boundary', 'any', 203, true),
  ('PowerDI™ 123', 'CP', 'word_boundary', 'any', 204, true),
  ('QFN', 'IP', 'word_boundary', 'any', 205, true),
  ('QFP', 'IP', 'word_boundary', 'any', 206, true),
  ('Radial', 'TH', 'word_boundary', 'any', 207, true),
  ('RJ45', 'TH', 'word_boundary', 'any', 208, true),
  ('RJ-45', 'TH', 'word_boundary', 'any', 209, true),
  ('SC70', 'CP', 'word_boundary', 'any', 210, true),
  ('SC-70', 'CP', 'word_boundary', 'any', 211, true),
  ('SC705', 'CP', 'word_boundary', 'any', 212, true),
  ('SC70-5', 'CP', 'word_boundary', 'any', 213, true),
  ('SC70-6', 'CP', 'word_boundary', 'any', 214, true),
  ('SC74A', 'CP', 'word_boundary', 'any', 215, true),
  ('SC-74A', 'CP', 'word_boundary', 'any', 216, true),
  ('SC76-2', 'CP', 'word_boundary', 'any', 217, true),
  ('SMA', 'CP', 'word_boundary', 'any', 218, true),
  ('SMB', 'CP', 'word_boundary', 'any', 219, true),
  ('SMC', 'IP', 'word_boundary', 'any', 220, true),
  ('SMCJ', 'IP', 'word_boundary', 'any', 221, true),
  ('SMT 0ZCH Series PTC resettable, 30V, I Hold=200mA, I Trip=400mA @ 23°C', 'CP', 'word_boundary', 'any', 222, true),
  ('SMT, CMOS Clock Oscillator with Enable, 3.3Vdc, 50.000 MHz', 'CPEXP', 'word_boundary', 'any', 223, true),
  ('SO14', 'IP', 'word_boundary', 'any', 224, true),
  ('SO-14', 'IP', 'word_boundary', 'any', 225, true),
  ('SO16', 'IP', 'word_boundary', 'any', 226, true),
  ('SO-16', 'IP', 'word_boundary', 'any', 227, true),
  ('SO4', 'CPEXP', 'word_boundary', 'any', 228, true),
  ('SO6', 'CPEXP', 'word_boundary', 'any', 229, true),
  ('SO8', 'CPEXP', 'word_boundary', 'any', 230, true),
  ('SO-8', 'CPEXP', 'word_boundary', 'any', 231, true),
  ('sod123', 'CP', 'word_boundary', 'any', 232, true),
  ('SOD-123', 'CP', 'word_boundary', 'any', 233, true),
  ('SOD-123F', 'CP', 'word_boundary', 'any', 234, true),
  ('SOD123W', 'CP', 'word_boundary', 'any', 235, true),
  ('SOD-123W', 'CP', 'word_boundary', 'any', 236, true),
  ('SOD128', 'CP', 'word_boundary', 'any', 237, true),
  ('SOD-128-2', 'CP', 'word_boundary', 'any', 238, true),
  ('SOD323', 'CP', 'word_boundary', 'any', 239, true),
  ('SOD-323', '0402', 'word_boundary', 'any', 240, true),
  ('SOD-323F', '0402', 'word_boundary', 'any', 241, true),
  ('SOD523', 'CP', 'word_boundary', 'any', 242, true),
  ('SOD80', 'CP', 'word_boundary', 'any', 243, true),
  ('SOD-9223', '0402', 'word_boundary', 'any', 244, true),
  ('SOD923', '0402', 'word_boundary', 'any', 245, true),
  ('SOD-923', '0402', 'word_boundary', 'any', 246, true),
  ('SOIC16', 'IP', 'word_boundary', 'any', 247, true),
  ('soic8', 'CPEXP', 'word_boundary', 'any', 248, true),
  ('SOIC-8', 'CPEXP', 'word_boundary', 'any', 249, true),
  ('SOP4', 'CPEXP', 'word_boundary', 'any', 250, true),
  ('SOP-4', 'CPEXP', 'word_boundary', 'any', 251, true),
  ('SOT143B', 'CP', 'word_boundary', 'any', 252, true),
  ('SOT223', 'IP', 'word_boundary', 'any', 253, true),
  ('SOT-223', 'IP', 'word_boundary', 'any', 254, true),
  ('SOT23', 'CP', 'word_boundary', 'any', 255, true),
  ('sot-23', 'CP', 'word_boundary', 'any', 256, true),
  ('SOT-23-3', 'CP', 'word_boundary', 'any', 257, true),
  ('SOT25', 'CP', 'word_boundary', 'any', 258, true),
  ('SOT-25-5', 'CP', 'word_boundary', 'any', 259, true),
  ('SOT26', 'CP', 'word_boundary', 'any', 260, true),
  ('SOT323', '0402', 'word_boundary', 'any', 261, true),
  ('SOT-323', '0402', 'word_boundary', 'any', 262, true),
  ('SOT353', 'CP', 'word_boundary', 'any', 263, true),
  ('SOT363', 'CP', 'word_boundary', 'any', 264, true),
  ('SOT-363', 'CP', 'word_boundary', 'any', 265, true),
  ('SOT5', 'CP', 'word_boundary', 'any', 266, true),
  ('SOT523', 'CP', 'word_boundary', 'any', 267, true),
  ('SOT-583', '0402', 'word_boundary', 'any', 268, true),
  ('SOT-7538', 'CP', 'word_boundary', 'any', 269, true),
  ('SOT-89', 'CPEXP', 'word_boundary', 'any', 270, true),
  ('SOT9X3', '0402', 'word_boundary', 'any', 271, true),
  ('SOW16', 'IP', 'word_boundary', 'any', 272, true),
  ('SOW-16', 'IP', 'word_boundary', 'any', 273, true),
  ('SOW20', 'IP', 'word_boundary', 'any', 274, true),
  ('SOW28', 'IP', 'word_boundary', 'any', 275, true),
  ('SSMINI2', 'CP', 'word_boundary', 'any', 276, true),
  ('SSOP28', 'IP', 'word_boundary', 'any', 277, true),
  ('SSOP-28', 'IP', 'word_boundary', 'any', 278, true),
  ('SSOP5', 'CP', 'word_boundary', 'any', 279, true),
  ('T/H', 'TH', 'word_boundary', 'any', 280, true),
  ('TERM BLOCK', 'TH', 'word_boundary', 'any', 281, true),
  ('TERM BLOCK HDR', 'TH', 'word_boundary', 'any', 282, true),
  ('TH', 'TH', 'word_boundary', 'any', 283, true),
  ('TH,', 'TH', 'word_boundary', 'any', 284, true),
  ('Through hole', 'TH', 'word_boundary', 'any', 285, true),
  ('Thru-Hole', 'TH', 'word_boundary', 'any', 286, true),
  ('THT', 'TH', 'word_boundary', 'any', 287, true),
  ('TO-236-3', 'CP', 'word_boundary', 'any', 288, true),
  ('TO236AB', 'CP', 'word_boundary', 'any', 289, true),
  ('TO-236AB', 'CP', 'word_boundary', 'any', 290, true),
  ('TO252', 'IP', 'word_boundary', 'any', 291, true),
  ('TO252-3', 'IP', 'word_boundary', 'any', 292, true),
  ('TO263', 'IP', 'word_boundary', 'any', 293, true),
  ('TO-263', 'IP', 'word_boundary', 'any', 294, true),
  ('to-268', 'IP', 'word_boundary', 'any', 295, true),
  ('TO92', 'TH', 'word_boundary', 'any', 296, true),
  ('TO92-3', 'TH', 'word_boundary', 'any', 297, true),
  ('TQFP', 'IP', 'word_boundary', 'any', 298, true),
  ('TQFP144', 'IP', 'word_boundary', 'any', 299, true),
  ('TSOT-6', 'CP', 'word_boundary', 'any', 300, true),
  ('TSSOP14', 'IP', 'word_boundary', 'any', 301, true),
  ('TSSOP-14', 'CPEXP', 'word_boundary', 'any', 302, true),
  ('TSSOP16', 'IP', 'word_boundary', 'any', 303, true),
  ('TSSOP-16', 'IP', 'word_boundary', 'any', 304, true),
  ('TSSOP20', 'IP', 'word_boundary', 'any', 305, true),
  ('TSSOP24', 'IP', 'word_boundary', 'any', 306, true),
  ('TSSOP48', 'IP', 'word_boundary', 'any', 307, true),
  ('TUMD2M', 'CP', 'word_boundary', 'any', 308, true),
  ('VMN2M', '0402', 'word_boundary', 'any', 309, true),
  ('WSON8', 'CP', 'word_boundary', 'any', 310, true),
  ('X1-DFN100', '0402', 'word_boundary', 'any', 311, true),
  ('TSMT3', 'CP', 'word_boundary', 'any', 312, true),
  ('PICOSTAR', '0402', 'word_boundary', 'any', 313, true),
  ('SOT-26', 'CP', 'word_boundary', 'any', 314, true),
  ('1008', 'CP', 'word_boundary', 'any', 315, true),
  ('1005', '0402', 'word_boundary', 'any', 316, true),
  ('SOT-25', 'CP', 'word_boundary', 'any', 317, true),
  ('TO-277A', 'CPEXP', 'word_boundary', 'any', 318, true),
  ('8-MSOP', 'CPEXP', 'word_boundary', 'any', 319, true),
  ('1806', 'CP', 'word_boundary', 'any', 320, true),
  ('DO-214BA', 'CP', 'word_boundary', 'any', 321, true),
  ('806', 'CP', 'word_boundary', 'any', 322, true),
  ('16-TSSOP', 'IP', 'word_boundary', 'any', 323, true);

-- PART 3 of 3: VBA-sourced pricing settings ------------------------------
UPDATE public.app_settings
SET value = value
    || jsonb_build_object('component_markup_pct', 30)
    || jsonb_build_object('pcb_markup_pct', 30)
    || jsonb_build_object('default_shipping', 200)
    || jsonb_build_object('labour_rate_per_hour', 130)
    || jsonb_build_object('smt_rate_per_hour', 165)
    || jsonb_build_object('_vba_sourced', true)
    || jsonb_build_object('_vba_sourced_at', '2026-04-15'),
    updated_at = NOW()
WHERE key = 'pricing';

COMMIT;
